#!/bin/bash


echo start: $0

source ~/rosenv
source ~/ws_baxter/devel/setup.bash
source ~/ws_alvar/devel/setup.bash --extend

# left_hand, right_hand or head
arm=$LIMB
gain=0

echo LIMB $LIMB ARM $arm ROS_IP $ROS_IP ROS_MASTER_URI $ROS_MASTER_URI

set -xv

# temporarily disabled for sim
rosrun ar_track_alvar camera_controlx.py -o ${arm}_camera -r 1280x800 -g $gain

while true
do
  roslaunch ./alvar_baxter_vxlab.launch limb:="${arm}"
  sleep 5
done
