#!/bin/bash

mkdir -p navigation_ws
(
cd navigation_ws
rm -rf navigation
git clone https://github.com/ros-planning/navigation.git
)
# Last known working version for ros-planning/navigation.git
#RUN git checkout 73d46b69e20a039f8a35a3f78145ac84a643720b

cp -r mobility_base_2dnav navigation_ws/navigation/mobility_base_2dnav
