#!/bin/bash

mkdir -p navigation_ws
(
cd navigation_ws
rm -rf navigation
git clone https://github.com/ros-planning/navigation.git
cd navigation
git checkout 73d46b69e20a039f8a35a3f78145ac84a643720b
)
# Last known working version for ros-planning/navigation.git

cp -r mobility_base_2dnav navigation_ws/navigation/mobility_base_2dnav
cp amcl_omni.launch ./navigation_ws/navigation/amcl/examples/amcl_omni.launch
