#!/bin/bash
get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     # While $SOURCE is a symlink, resolve it
     while [ -h "$SOURCE" ]; do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     echo "script directory is $SCRIPTDIR"
}
set -xv
# SCRIPTDIR=...
get_script_dir

docker rm -f novnc
docker rm -f rviz

docker network rm vxlab
docker network create --subnet 10.42.170.0/24 --gateway 10.42.170.254 vxlab
#docker network create vxlab

if [ ! "$(docker ps -q -f name=novnc)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=novnc)" ]; then
        # cleanup
        docker rm novnc
    fi
    # run your container
    docker run --network vxlab --name novnc --rm -p 8080:8080 theasp/novnc 2>&1 > x11.log &
fi

# Not accessible on CSRack blades without VPN
#docker run --network vxlab --name rviz --rm -p 8082:8080 theasp/novnc 2>&1 > x11.log &

INAME=${1:-vxlab-rosie}
echo INAME $INAME

CNAME=vxlab-rosie

docker rm -f $CNAME

docker run --network vxlab -v $SCRIPTDIR/rosie:/root/rosie --name $CNAME -it -e DISPLAY=novnc:0 $INAME
