#!/bin/bash

cp vxlab.world ~/ws_baxter/src/gazebo_ros_pkgs/gazebo_plugins/test2/worlds/empty.world

cd ~/ws_baxter
#HOSTNAME=`hostname`
HOSTNAME=127.0.0.1
#export ROS_IP=${HOSTNAME}.vx.rmit.edu.au
export ROS_IP=${HOSTNAME}
#export ROS_MASTER_URI=http://${HOSTNAME}.vx.rmit.edu.au:11311
export ROS_MASTER_URI=http://${HOSTNAME}:11311
source devel/setup.bash
roslaunch mobility_base_gazebo mobility_base_empty_world.launch baxter:=true
#roslaunch baxter_gazebo baxter_world.launch
