#!/bin/bash
#source /opt/ros/kinetic/setup.bash
#source ~/ros/baxter/devel/setup.bash
source ~/marker_recognition/devel/setup.bash
export ROS_MASTER_URI=http://redsim_a:11311
export ROS_IP=10.234.2.170
