#!/bin/bash
ROS_MASTER_IP=`~/rosie/hostlookup vxlab-blue`
ROS_MASTER_URI=http://${ROS_MASTER_IP}:11311

rostopic pub -1 /blue/move_base_simple/goal geometry_msgs/PoseStamped "{header: {stamp: now, frame_id: 'map'}, pose: {position: {x: $1, y: $2}, orientation: {z: $3, w: $4}}}"

round() {
  printf "%.${2}f" "${1}"
}

function abs() {
    [[ $(($@)) -lt 0 ]] && echo "$(($@*-1))" || echo "$(($@))"
}

FINISHED=false
while [ "$FINISHED" == false ]
do
  #Position
  x="$(echo $(rostopic echo -n1 /blue/move_base/feedback/feedback/base_position/pose/position/x || 0)|tr -d '\n')"
  y="$(echo $(rostopic echo -n1 /blue/move_base/feedback/feedback/base_position/pose/position/y)|tr -d '\n')"

  #Orientation
  z="$(echo $(rostopic echo -n1 /blue/move_base/feedback/feedback/base_position/pose/orientation/z)|tr -d '\n')"
  w="$(echo $(rostopic echo -n1 /blue/move_base/feedback/feedback/base_position/pose/orientation/w)|tr -d '\n')"

  xDiff=$(abs $(round $(awk '{print $1-$2}' <<<"$1 $x") 0))
  yDiff=$(abs $(round $(awk '{print $1-$2}' <<<"$2 $y") 0))
  zDiff=$(abs $(round $(awk '{print $1-$2}' <<<"$3 $z") 0))
  wDiff=$(abs $(round $(awk '{print $1-$2}' <<<"$4 $w") 0))

  if  [[ "$xDiff" -le 1 && "$yDiff" -le 1  && "$zDiff" -le 1 && "$wDiff" -le 1 ]]; then
    FINISHED=true
  fi

  sleep 5
done

