#!/bin/bash

ROS_MASTER_IP=`~/rosie/hostlookup vxlab-blue`
ROS_MASTER_URI=http://${ROS_MASTER_IP}:11311

rostopic pub -1 /blue/move_base_simple/goal geometry_msgs/PoseStamped '{header: {stamp: now, frame_id: "map"}, pose: {position: {x: -5.0, y: 3.0, z: 0.0}, orientation: {z: 1.0, w: 1.0}}}'
