#!/bin/bash

ROS_MASTER_IP=`~/rosie/hostlookup vxlab-rosie`
ROS_MASTER_URI=http://${ROS_MASTER_IP}:11311

rostopic pub -1 /rosie/move_base_simple/goal geometry_msgs/PoseStamped '{header: {stamp: now, frame_id: "map"}, pose: {position: {x: 0.0, y: 0.0, z: 0.631}, orientation: {w: 1.0}}}'
