#!/bin/bash

# Delete models if already spawned
rosservice call /gazebo/delete_model human1
rosservice call /gazebo/delete_model human2
rosservice call /gazebo/delete_model human3
rosservice call /gazebo/delete_model human4

# Spawn new models
# Window
rosrun gazebo_ros spawn_model -urdf -file ~/rosie/models/human1_colored.urdf -model human1 -x -6.0 -y 3.0 -z 1.0
# Little Room
rosrun gazebo_ros spawn_model -urdf -file ~/rosie/models/human1_colored.urdf -model human2 -x -5.5 -y -5.0 -z 1.0 -Y 1.5
# Govlab
rosrun gazebo_ros spawn_model -urdf -file ~/rosie/models/human1_colored.urdf -model human3 -x 5.5 -y -2.0 -z 1.0 -Y 3.1
# Door
rosrun gazebo_ros spawn_model -urdf -file ~/rosie/models/human1_colored.urdf -model human4 -x 0.5 -y 6.0 -z 1.0 -Y -1.5