#!/bin/bash
rosservice call /gazebo/delete_model mir

source ~/mir_ws/devel/setup.bash
source ~/rosie/rosenv.bash

roslaunch ~/rosie/mir100_minimal_vxlab.launch robot_x:=2.0 robot_y:=2.0 robot_yaw:=0.0 &

sleep 5
