#!/bin/bash

ln -s ~/rosie/rviz_settings ~/.rviz

cp ~/rosie/MobilityBasePlugin_ns.cpp /root/mb_ws/src/mobility_base_simulator/mobility_base_gazebo_plugins/src/MobilityBasePlugin.cpp

cp ~/rosie/baxter_sim_controllers_ns.yaml /root/ws_baxter/src/baxter_simulator/baxter_sim_hardware/config/baxter_sim_controllers.yaml

cp ~/rosie/tuck_arms.py ~/ws_baxter/src/baxter_tools/scripts/tuck_arms.py
cp ~/rosie/limb.py ~/ws_baxter/src/baxter_interface/src/baxter_interface/
cp ~/rosie/head.py ~/ws_baxter/src/baxter_interface/src/baxter_interface/

# namespace /rosie
cp ~/rosie/baxter_sim_kinematics_ns.launch /root/ws_baxter/src/baxter_simulator/baxter_sim_kinematics/launch/baxter_sim_kinematics.launch

# namespace /rosie
cp ~/rosie/baxter_sdk_control_ns.launch /root/ws_baxter/src/baxter_simulator/baxter_sim_hardware/launch/baxter_sdk_control.launch

# Fix head collision model causing arms not to untuck(?!)
cp ~/rosie/baxter_base_ns.gazebo.xacro ~/ws_baxter/src/baxter_common/baxter_description/urdf/baxter_base/
cp ~/rosie/baxter_base.urdf.xacro ~/ws_baxter/src/baxter_common/baxter_description/urdf/baxter_base/

cp ~/rosie/mobility_base_ns.urdf.xacro /root/mb_ws/src/mobility_base_ros/mobility_base_description/urdf/mobility_base.urdf.xacro

#cp ~/rosie/baxter_emulator.cpp /root/ws_baxter/src/baxter_simulator/baxter_sim_hardware/src/baxter_emulator.cpp

cp ~/rosie/baxter_gazebo_ros_control_plugin_ns.cpp ~/ws_baxter/src/baxter_simulator/baxter_gazebo/src/baxter_gazebo_ros_control_plugin.cpp

mkdir -p ~/.ignition/fuel
cp ~/rosie/ignition.fuel.config.yaml ~/.ignition/fuel/config.yaml

cd ~/ws_baxter
catkin_make
