#!/bin/bash

rosservice call /gazebo/delete_model marker0
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock50_obj/model.sdf -model marker0 -x 3.0 -y 0.0 -z 0.0

rosservice call /gazebo/delete_model marker_s0
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblockgrab_obj/model.sdf -model marker_s0 -x 2.8 -y 0.0 -z 0.9
