#!/bin/bash
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock_obj/model.sdf -model marker0 -x 3.0 -y 1.5 -z 0.0
#rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock_obj/model.sdf -model marker1 -x 3.0 -y 1.5 -z 0.5
#rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock_obj/model.sdf -model marker1 -x 3.0 -y 1.5 -z 1.0
