#!/bin/bash
while true; do
  # Window
  ./navgoal/blue_delivery -5.0 3.0 1.0 1.0
  # Little Room
  ./navgoal/blue_delivery -5.5 -4.0 0.0 1.0
  # Govlab
  ./navgoal/blue_delivery 7.0 -2.0 -1.0 1.0
  # Door
  ./navgoal/blue_delivery 0.5 5.0 1.0 0.0
done
