#!/bin/bash

cd ~/ws_baxter
#HOSTNAME=`hostname`
#HOSTNAME=127.0.0.1
#export ROS_IP=${HOSTNAME}.vx.rmit.edu.au
#export ROS_IP=${HOSTNAME}
#export ROS_MASTER_URI=http://${HOSTNAME}.vx.rmit.edu.au:11311
#export ROS_MASTER_URI=http://${HOSTNAME}:11311

export MB_LASER_BIRDCAGE_R2000=1
export MB_LASER_BIRDCAGE_R2000_FREQ=50
export MB_LASER_BIRDCAGE_R2000_SAMPLES=3600

source ~/rosie/rosenv.bash

~/rosie/installconfig

{ sleep 3 ; tail -f ~/.ros/log/latest/* ; sleep 10; /root/rosie/checkconfig ; } &

export LIBGL_ALWAYS_INDIRECT=0

roslaunch /root/rosie/vxlab_sim.launch baxter:=true paused:=true || /bin/sleep 600
