#!/bin/bash 
#cp resolv.conf docker-opengl/etc/resolv.conf
#cp graphical-app-launcher.conf noVNC.conf x11vnc.conf xdummy.conf docker-opengl/etc/supervisor/conf.d/
#cp graphical-app-launcher.conf noVNC.conf x11vnc.conf xdummy.conf 

touch 02proxy

docker build -t "vxlab-rosie-melodic" -f Dockerfile.melodic . --network host 2>&1 | tee build.log
#docker build -t "vxlab-rosie-trusty" -f Dockerfile.trusty . --network host 2>&1 | tee build.log
#docker build -t "vxlab-rosie-xenial" -f Dockerfile.xenial . --network host 2>&1 | tee build.log

#docker build -t "vxlab-rosie-wily" -f Dockerfile.wily . --network host 2>&1 | tee build.log

#docker build -t "vxlab-rosie-nav" . -f Dockerfile.nav --network host 2>&1 | tee build.log

##docker build -t "vxlab-rosie-artful" -f Dockerfile.artful . --network host 2>&1 | tee build.log

#sudo docker build -t "vxlab-baxter" . --no-cache
