FROM ros:melodic-ros-core

# VXLab local proxy
COPY 02proxy /etc/apt/apt.conf.d/02proxy

# Fix ROS keys
RUN apt-key del 421C365BD9FF1F717815A3895523BAEEB01FA116
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

RUN apt update && \
    # Install some basic dependencies
    apt install -y \
        iproute2 host wget less sudo vim-tiny iputils-ping telnet lsof psmisc

RUN apt-get update && apt -y dist-upgrade && apt-get install -y \
    build-essential python-catkin-tools python-catkin-lint python-rosdep

# Create ROS workspace
COPY . /ws/src/mir_robot
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep install --from-paths src -i -y --rosdistro melodic

# Why is this not installed already?!
RUN apt update && apt install -y \
    ros-melodic-gazebo-plugins

RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
    catkin init && \
    catkin config --install -j 1 -p 1 && \
    catkin_make"

#RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
#    catkin init && \
#    catkin config --install -j 1 -p 1 && \
#    catkin build --limit-status-rate 0.1 --no-notify && \
#    catkin build --limit-status-rate 0.1 --no-notify --make-args tests"
