version: "3.5"
services:
    #novnc:
    #    container_name: novnc
    #    image: theasp/novnc
    #    networks:
    #      vxlab:
    #    ports:
    #      - "8080:8080"
    vxlab-blue:
        container_name: vxlab-blue
        build:
          context: .
          dockerfile: Dockerfile-melodic
          #network: host
        networks:
          vxlab:
        volumes:
        - type: bind
          source: ./blue
          target: /root/mir100
        environment:
          DISPLAY: novnc:0
        entrypoint: ["sh", "-c", "sleep 21000"]

networks:
    vxlab:
      external: true
      name: vxlab

#networks:
    #vxlab:
        #name: vxlab
        #ipam:
            #config:
              #- subnet: "10.42.170.0/24"
                #- gateway: "10.42.170.254"
