#!/bin/bash


echo start: $0

source ~/rosenv
source ~/ws_baxter/devel/setup.bash
source ~/ws_alvar/devel/setup.bash --extend

arm="right"
gain=0

#case $1 in
#"right") arm=$1
#;;
#"left") arm=$1
#;;
#*) echo "usage: $0 left|right" 
#;;
#esac

echo LIMB $LIMB ARM $arm ROS_IP $ROS_IP ROS_MASTER_URI $ROS_MASTER_URI

set -xv

rosrun ar_track_alvar camera_controlx.py -o ${arm}_hand_camera -r 1280x800 -g $gain

roslaunch ./alvar_baxter_vxlab.launch limb:="${arm}"
